version: 2
jobs:
  build:

    working_directory: ~/wildflyswarm-api-auth

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: java-rest-xmasauth-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: java-rest-xmasauth-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_artifacts:
          path: target/java-rest-xmasauth-1.0.0-SNAPSHOT.jar